spring:
  application:
    name: order
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/shopc-db
    username: user
    password: pwd

logging:
  level:
    root: INFO
    se.magnus: DEBUG
shop:
  customer:
    api:
      url: http://localhost:8080/ms/customer
server:
  port: 8080
  servlet:
    context-path: /ms/order

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

spring.config.activate.on-profile: docker

spring.datasource:
  url: jdbc:mysql://mysql/shopc-db
